name: everli_client_v2
description: "An AI powered event management and planning app."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # local packages
  responsive_layout:
    path: packages/responsive_layout

  # Online packages
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  sqflite: ^2.3.3+1
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  http: ^1.2.1
  path: ^1.9.0
  path_provider: ^2.1.3
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  equatable: ^2.0.5
  google_nav_bar: ^5.0.6
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  flutter_staggered_grid_view: ^0.7.0
  supabase_flutter: ^2.5.6
  cached_network_image: ^3.3.1
  gallery_picker: ^0.5.1
  image_picker: ^1.1.2
  uuid: ^4.4.0
  awesome_notifications: ^0.9.3+1
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.5.0
  pinput: ^5.0.0
  country_picker: ^2.0.26
  logger: ^2.3.0
  dotted_border: ^2.1.0

  # Flutter app Icon
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/app_icon/
    - assets/lottie/
    - .env

# APP ICON
flutter_icons:
  image_path: assets/app_icon/Everli_logo.png
  android: "launcher_icon"
  ios: "AppIcon"
  remove_alpha_ios: true
  min_sdk_ios: 21
